//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Actividad_Integradora_7_Problema_2.ServiceValidaDNI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceValidaDNI.ValidaDniWsSoap")]
    public interface ValidaDniWsSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento valor del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidaDNI", ReplyAction="*")]
        Actividad_Integradora_7_Problema_2.ServiceValidaDNI.ValidaDNIResponse ValidaDNI(Actividad_Integradora_7_Problema_2.ServiceValidaDNI.ValidaDNIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidaDNI", ReplyAction="*")]
        System.Threading.Tasks.Task<Actividad_Integradora_7_Problema_2.ServiceValidaDNI.ValidaDNIResponse> ValidaDNIAsync(Actividad_Integradora_7_Problema_2.ServiceValidaDNI.ValidaDNIRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidaDNIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidaDNI", Namespace="http://tempuri.org/", Order=0)]
        public Actividad_Integradora_7_Problema_2.ServiceValidaDNI.ValidaDNIRequestBody Body;
        
        public ValidaDNIRequest() {
        }
        
        public ValidaDNIRequest(Actividad_Integradora_7_Problema_2.ServiceValidaDNI.ValidaDNIRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidaDNIRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string valor;
        
        public ValidaDNIRequestBody() {
        }
        
        public ValidaDNIRequestBody(string valor) {
            this.valor = valor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidaDNIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidaDNIResponse", Namespace="http://tempuri.org/", Order=0)]
        public Actividad_Integradora_7_Problema_2.ServiceValidaDNI.ValidaDNIResponseBody Body;
        
        public ValidaDNIResponse() {
        }
        
        public ValidaDNIResponse(Actividad_Integradora_7_Problema_2.ServiceValidaDNI.ValidaDNIResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidaDNIResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ValidaDNIResult;
        
        public ValidaDNIResponseBody() {
        }
        
        public ValidaDNIResponseBody(bool ValidaDNIResult) {
            this.ValidaDNIResult = ValidaDNIResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ValidaDniWsSoapChannel : Actividad_Integradora_7_Problema_2.ServiceValidaDNI.ValidaDniWsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValidaDniWsSoapClient : System.ServiceModel.ClientBase<Actividad_Integradora_7_Problema_2.ServiceValidaDNI.ValidaDniWsSoap>, Actividad_Integradora_7_Problema_2.ServiceValidaDNI.ValidaDniWsSoap {
        
        public ValidaDniWsSoapClient() {
        }
        
        public ValidaDniWsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ValidaDniWsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidaDniWsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidaDniWsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Actividad_Integradora_7_Problema_2.ServiceValidaDNI.ValidaDNIResponse Actividad_Integradora_7_Problema_2.ServiceValidaDNI.ValidaDniWsSoap.ValidaDNI(Actividad_Integradora_7_Problema_2.ServiceValidaDNI.ValidaDNIRequest request) {
            return base.Channel.ValidaDNI(request);
        }
        
        public bool ValidaDNI(string valor) {
            Actividad_Integradora_7_Problema_2.ServiceValidaDNI.ValidaDNIRequest inValue = new Actividad_Integradora_7_Problema_2.ServiceValidaDNI.ValidaDNIRequest();
            inValue.Body = new Actividad_Integradora_7_Problema_2.ServiceValidaDNI.ValidaDNIRequestBody();
            inValue.Body.valor = valor;
            Actividad_Integradora_7_Problema_2.ServiceValidaDNI.ValidaDNIResponse retVal = ((Actividad_Integradora_7_Problema_2.ServiceValidaDNI.ValidaDniWsSoap)(this)).ValidaDNI(inValue);
            return retVal.Body.ValidaDNIResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Actividad_Integradora_7_Problema_2.ServiceValidaDNI.ValidaDNIResponse> Actividad_Integradora_7_Problema_2.ServiceValidaDNI.ValidaDniWsSoap.ValidaDNIAsync(Actividad_Integradora_7_Problema_2.ServiceValidaDNI.ValidaDNIRequest request) {
            return base.Channel.ValidaDNIAsync(request);
        }
        
        public System.Threading.Tasks.Task<Actividad_Integradora_7_Problema_2.ServiceValidaDNI.ValidaDNIResponse> ValidaDNIAsync(string valor) {
            Actividad_Integradora_7_Problema_2.ServiceValidaDNI.ValidaDNIRequest inValue = new Actividad_Integradora_7_Problema_2.ServiceValidaDNI.ValidaDNIRequest();
            inValue.Body = new Actividad_Integradora_7_Problema_2.ServiceValidaDNI.ValidaDNIRequestBody();
            inValue.Body.valor = valor;
            return ((Actividad_Integradora_7_Problema_2.ServiceValidaDNI.ValidaDniWsSoap)(this)).ValidaDNIAsync(inValue);
        }
    }
}
